// <auto-generated />
namespace PerformingArtsApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class studentsperformances : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(studentsperformances));
        
        string IMigrationMetadata.Id
        {
            get { return "202403172337447_students-performances"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
